Updated k-tau Implementation
stgeke/public-nekRS pull request #1
Opened 2023-01-14 03:22 UTC by nandu90

Updates to the source terms in the k-tau formulation (formulation by Ananias Tomboulides)

- Requires wall distance to be passed from Nek5000 (.usr) file to nekRS (o_ywd array in RANSktau.cpp) 
- The ktauChannel example case (.usr) is updated to ensure wall distance is passed - needs to be done only once

2023-01-14 08:44 UTC, stgeke requested changes

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +          const dfloat kk = max(0.0,K[id]);
Please use `fmax` instead of `max`

2023-01-14 08:44 UTC, stgeke commented on examples/ktauChannel/channel.usr
> +      if(istep.eq.0)then
You can move all this to `usrdat3`

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +          const dfloat kSrc = min(mu_t * stMag2, 10.0 * Y_k * kk);
Please use `fmin`

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +          const dfloat kSrc = min(mu_t * stMag2, 10.0 * Y_k * kk);
Does it make sense to use a parameter instead of a hardwired value like `10`?

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	  const dfloat cr_tau = p_beta0 * yw * yw * rho / mue / 6.0;
Please use store `mue / rho / yw` and reuse where needed including the inverse value.

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	  if (tau <= p_tiny){
I suggest to use `<` instead of `<=`.

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	    tauDiag = G_wp + S_tau/tau - S_w0;
In several location you use `1/tau`. You should cache it i.e. `itau = 1/tau` and reuse it. On GPUs a div-op is very expensive so you want to minimize them.

2023-01-14 08:44 UTC, stgeke commented on kernels/plugins/mue.okl
> +      const dfloat k = max(0.0,K[n]);
Please use `fmax`

2023-01-14 08:44 UTC, stgeke commented on src/plugins/RANSktau.cpp
> -  limitKernel(mesh->Nelements * mesh->Np, o_k, o_tau);
Is the limitKernel used somewhere else? If not please remove it from the source.

2023-01-14 21:48 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +          const dfloat kk = max(0.0,K[id]);
Changed to fmax

2023-01-14 21:49 UTC, nandu90 commented on examples/ktauChannel/channel.usr
> +      if(istep.eq.0)then
moved to usrdat3

2023-01-14 21:49 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +          const dfloat kSrc = min(mu_t * stMag2, 10.0 * Y_k * kk);
Changed to fmin

2023-01-14 21:52 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +          const dfloat kSrc = min(mu_t * stMag2, 10.0 * Y_k * kk);
Yes, this term limits the TKE production term when it may go unreasonably high during initial transients and prevents simulation from diverging. Values greater than 10*Y_k (dissipation) are not expected in the converged solution. 

User control is not needed here and a factor of 10 is appropriate (consistent with Ananias' implementation in Nek5000)

2023-01-14 21:54 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	  const dfloat cr_tau = p_beta0 * yw * yw * rho / mue / 6.0;
Thanks for the suggestion. New commit caches this factor (and its inverse) for re-use.

2023-01-14 21:54 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	  if (tau <= p_tiny){
Changed

2023-01-14 21:56 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	    tauDiag = G_wp + S_tau/tau - S_w0;
Thanks. The latest commit use itau wherever I can. 

Note that i added p_tiny to calculate tau inverse. This was necessary especially for the TKE production term (Y_k), else the simulation diverged if tau got too low.

2023-01-14 21:58 UTC, nandu90 commented on kernels/plugins/mue.okl
> +      const dfloat k = max(0.0,K[n]);
Changed

2023-01-14 21:58 UTC, nandu90 commented on src/plugins/RANSktau.cpp
> -  limitKernel(mesh->Nelements * mesh->Np, o_k, o_tau);
No, it is not used anywhere now. Removed entirely from source in latest commit

2023-01-17 19:25 UTC, stgeke commented
Merged to internal repo.

2023-01-17 19:25 UTC, closed without merging