CI test case for ktauChannel
stgeke/public-nekRS pull request #2
Opened 2023-02-16 07:45 UTC by nandu90

Included a minor change in RANSktauComputeHex3D.okl. The if condition for Scoefn is updated based on Ananias' recommendation

2023-02-16 08:46 UTC, stgeke requested changes

2023-02-16 08:46 UTC, stgeke commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	  const dfloat cr_edd = 4.4 * mue;
Is the `4.4` a model parameter or a universal factor?

2023-02-16 08:46 UTC, stgeke commented on examples/ktauChannel/ci.inc
> +  dragScaleKernel(mesh->Nelements,
Merge the scaling into the drag kernel.

2023-02-16 08:46 UTC, stgeke commented on examples/ktauChannel/ci.inc
> +	     nrs->o_EToB,
Pass `mesh->o_EToB` and add a kernel argument `bId` to denote the boundary ID. This way a user can specify which bID he wants to use to compute the drag. You also need to multiply the output by `mesh->o_invLMM` instead of `1/JW`.

2023-02-16 08:46 UTC, stgeke commented on examples/ktauChannel/channel.par
> +boundaryTypeMap = wall, SYM
Why was this changed?

2023-02-16 08:46 UTC, stgeke commented on examples/ktauChannel/ci.inc
> +
You need to add
```
  oogs::startFinish(o_SijOij, 2*nrs->NVfields, nrs->fieldOffset, ogsDfloat, ogsAdd, nrs->gsh);
```
to make it C0.

2023-02-16 08:46 UTC, stgeke commented on examples/ktauChannel/channel.oudf
> +@kernel void dragScale(const dlong Nelements,
As discussed below this kernel should be merged into the drag kernel.

2023-02-16 08:46 UTC, stgeke commented on examples/ktauChannel/ci.inc
> +#define EPS 5e-2
Is this the correct relative error tolerance you want to use?

2023-02-16 17:40 UTC, nandu90 commented on kernels/plugins/RANSktauComputeHex3D.okl
> +	  const dfloat cr_edd = 4.4 * mue;
Its a universal factor. cr_edd corresponds to the inner edge of log-layer (boundary of log-layer and transition layer). That's where 4.4 comes from. The if block using cr_edd has to be activated only in the sub-log layer region. 

User control is not required.

2023-02-16 17:44 UTC, nandu90 commented on examples/ktauChannel/ci.inc
> +	     nrs->o_EToB,
Thanks! That's definitely a better way. I have passed `mesh->o_EToB`

At a later stage it would be a good idea to allow the user to pass bID array, similar to how we pass boundary objects to `torque_calc` in Nek5000, to enable drag calculation on multiple surfaces independently.

Thanks for pointing to `mesh->o_invLMM`. That had me confused for a while.

2023-02-16 17:45 UTC, nandu90 commented on examples/ktauChannel/channel.par
> +boundaryTypeMap = wall, SYM
An artifact of my experimentations. I have changed it back

2023-02-16 17:45 UTC, nandu90 commented on examples/ktauChannel/ci.inc
> +
Thanks for noting this. I have added the call

2023-02-16 17:45 UTC, nandu90 commented on examples/ktauChannel/channel.oudf
> +@kernel void dragScale(const dlong Nelements,
Merged

2023-02-24 06:19 UTC, nandu90 commented on examples/ktauChannel/ci.inc
> +#define EPS 5e-2
Decreased tol to 1e-2

2023-03-03 18:42 UTC, closed without merging